kafka:
  bootstrap-servers: 127.0.0.1:9092
  topic.request-topic: requesttopic2
  topic.requestreply-topic: replytopic2
  consumergroup: requestreplygorup2

spring:
  application:
    name: consumer

  kafka:
    producer:
      max:
        request:
          size: 231072000
      batch-size: 60000000
      buffer-memory: 60000000
    bootstrap-servers: 127.0.0.1:9092
    client-id: consumer
    consumer:
      group-id: requestreplygorup2
      auto-offset-reset: earliest
      enable-auto-commit: false