version: '3'

services: 
    productapp:
        build: .
        volumes:
            - ./:/var/www
        depends_on: 
            - productapp-mysql
            - productapp-redis

    productapp-nginx:
        build: ./.docker/nginx
        restart: always
        ports: 
            - "8001:80"
        volumes:
            - "./:/var/www"
        depends_on: 
            - productapp

    productapp-mysql:
        image: mysql:5.7.22
        command: --innodb-use-native-aio=0
        restart: always
        ports: 
            - "8011:3306"
        volumes:
            - "./.docker/dbdata:/var/lib/mysql"
        environment: 
            MYSQL_DATABASE: productapp
            MYSQL_ROOT_PASSWORD: root

    productapp-redis:
        image: redis:alpine
        expose: 
            - 6379

networks:
    default:
        external:
            name: microservices-network